on: push
jobs:
  init:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

  install-dependencies:
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        run: |
          yarn
          tar -czf node-modules.tar.gz node_modules/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node-modules.tar.gz

  lint:
    runs-on: self-hosted
    needs: install-dependencies
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: node_modules
      - run: |
          tar -xzf node-modules.tar.gz node_modules/
          yarn eslint '**/*.{ts,tsx}'

  # build:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '20'

  #     - name: Install dependencies
  #       run: yarn install

  #     - name: Setup JDK 17
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: '17'
  #         distribution: 'temurin'

  #     - name: Setup Android SDK
  #       uses: android-actions/setup-android@v3

  #     - name: Setup Gradle
  #       uses: gradle/gradle-build-action@v3

  #     - name: Build with Gradle
  #       run: cd android && ./gradlew build

  #     - name: Build Android App
  #       run: cd android && ./gradlew assembleRelease
